### ISSUE TITLE
`failed to create process` on Windows 8.1 64bit

### ISSUE THREAD

**Issue by salkinium** [ARMmbed/yotta_windows_installer#15]
The Yotta installer v0.1.4 runs and completes successfully, however, running yotta fails with `failed to create process`.

**Comment by BlackstoneEngineering** [comment]
Please provide details on the following:
1) what are the directories in C:\yotta ?
2) how are you running yotta? are you trying to run it from the command line or from the shortcut on the desktop / start menu?
3) Did you install all the dependencies, if so were any of them already installed on your machine?

**Comment by niklas-arm** [comment]
1. Sorry, I don't have that information, this happened on the computer of a hackathon participant, we didn't investigate it further, as another solution was found.
2. From the shortcut on the desktop.
3. This installer has dependencies? ಠ_ಠ

**Comment by BlackstoneEngineering** [comment]
Right, so closing this issue due to lack of information for proper debug, Also the installer has since been updated and should fix a number of these problems. 

In the future for debugging please provide a list of all files and folders in c:\yotta and a gist of `set` which should return all the environment variables.

**Comment by aamcampbell** [comment]
I've had the same issue. I thought maybe it was an installation issue, since I put it somewhere other than C:\yotta, so I tried it somewhere else, and then finally in C:\yotta. But I still get the same "failed to create process" message when I try running `yotta` or `yt`. 

My yotta installation folder contains:

```
 Directory of c:\yotta

01/04/2016  12:29 PM    <DIR>          .
01/04/2016  12:29 PM    <DIR>          ..
01/04/2016  12:29 PM    <DIR>          cmake-3.4.0-rc3-win32-x86
11/03/2015  11:21 AM        16,963,819 cmake-3.4.0-rc3-win32-x86.zip
01/04/2016  12:29 PM    <DIR>          gcc
11/03/2015  11:27 AM        98,465,351 gcc-arm-none-eabi-4_9-2015q3-20150921-win
32.zip
11/24/2014  02:07 PM           290,816 ninja.exe
08/20/2015  10:35 PM            33,354 p.ico
12/14/2015  06:30 PM             1,282 pip_install_yotta.bat
10/05/2015  08:45 AM               868 run_yotta.bat
01/04/2016  12:29 PM    <DIR>          workspace
01/04/2016  12:29 PM            72,680 yotta_uninstall.exe
               7 File(s)    115,828,170 bytes
```

I installed gcc, cMake, and ninja dependencies, but I skipped Python because I already have it (version 3.4). Host OS: Windows 7 64-bit.

**Comment by aamcampbell** [comment]
I was able to solve this particular error message by adding these two lines to [yotta inst]/run_yotta.bat:

    set YOTTA_PATH=C:\yotta
    set YOTTA_INSTALL_LOCATION=%YOTTA_PATH%

Maybe these two environment variables were supposed to be added to my system but were not? That might not be the root issue though; my yotta installation on this particular host computer has several other issues (e.g. it tries to use Python 3 to run .py files that have Python 2-syntax "throw" statements). It's on a development machine with tons of other software--I didn't encounter this issue on either of two systems that had fresher Windows installations.
